spring:
  datasource:
    url: jdbc:mysql://${local_ip}:3306/cursos?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  doc:
    packages-to-scan: com.formacion.controller
    paths-to-match: /**

eureka:
  client:
    service-url:
      defaultZone: http://${local_ip}:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: servicio-formacion

server:
  port: 7000
