spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productos?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
    client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      instance-id: servicio-productos

server:
  port: 8000
